name: build
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - CMakeLists.txt
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - CMakeLists.txt
  workflow_dispatch:

jobs:
  build-on-windows-amd64:
    name: Build on Windows AMD64 (MSVC)
    runs-on: windows-2025-vs2026
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=cl

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload Artifact
        uses: actions/upload-artifact@v5
        with:
          name: ProxyPass-windows-amd64-${{ github.sha }}
          path: bin/ProxyPass*
          retention-days: 15

  build-on-windows-arm64:
    name: Build on Windows ARM64 (MSVC)
    runs-on: windows-11-vs2026-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: arm64

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=cl

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload Artifact
        uses: actions/upload-artifact@v5
        with:
          name: ProxyPass-windows-arm64-${{ github.sha }}
          path: bin/ProxyPass*
          retention-days: 15

  build-on-linux-x86_64:
    name: Build on Linux X86_64 (GCC)
    runs-on: ubuntu-24.04
    container:
      image: gcc:15
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Install Dependencies
        run: apt-get update && apt-get install -y ninja-build cmake libssl-dev

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload Artifact
        uses: actions/upload-artifact@v5
        with:
          name: ProxyPass-linux-x86_64-${{ github.sha }}
          path: bin/ProxyPass*
          retention-days: 15

  build-on-linux-arm64:
    name: Build on Linux ARM64 (GCC)
    runs-on: ubuntu-24.04-arm
    container:
      image: gcc:15
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Install Dependencies
        run: apt-get update && apt-get install -y ninja-build cmake libssl-dev

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload Artifact
        uses: actions/upload-artifact@v5
        with:
          name: ProxyPass-linux-arm64-${{ github.sha }}
          path: bin/ProxyPass*
          retention-days: 15

  build-on-macos-arm64:
    name: Build on MacOS ARM64 (Apple Clang)
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Configure OpenSSL
        run: echo "OPENSSL_ROOT_DIR=$(brew --prefix openssl@3)" >> "$GITHUB_ENV"

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload Artifact
        uses: actions/upload-artifact@v5
        with:
          name: ProxyPass-macos-arm64-${{ github.sha }}
          path: bin/ProxyPass*
          retention-days: 15

  build-on-macos-intel:
    name: Build on MacOS X86_64 (Apple Clang)
    runs-on: macos-26-intel
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Configure OpenSSL
        run: echo "OPENSSL_ROOT_DIR=$(brew --prefix openssl@3)" >> "$GITHUB_ENV"

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload Artifact
        uses: actions/upload-artifact@v5
        with:
          name: ProxyPass-macos-intel-${{ github.sha }}
          path: bin/ProxyPass*
          retention-days: 15
